### ISSUE TITLE
Vagrant status failed with SSL Error

### ISSUE THREAD

**Issue by dspautz** [hysnsec/DevSecOps-Studio#81]
Vagrant 2.1.2

Linux doha 5.2.11-100.fc29.x86_64 #1 SMP Thu Aug 29 12:52:22 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux

725939562feed59dc4a94f044487fe57706177bf (HEAD -> master, origin/master, origin/HEAD) Merge pull request #74 from teacheraio/sample-scan-files

```bash
[user@localhost DevSecOps-Studio]$ vagrant status
Ignoring ffi-1.9.23 because its extensions are not built. Try: gem pristine ffi --version 1.9.23
Ignoring json-2.1.0 because its extensions are not built. Try: gem pristine json --version 2.1.0
Ignoring nokogiri-1.10.4 because its extensions are not built. Try: gem pristine nokogiri --version 1.10.4
Ignoring ruby-libvirt-0.7.1 because its extensions are not built. Try: gem pristine ruby-libvirt --version 0.7.1
Ignoring unf_ext-0.0.7.6 because its extensions are not built. Try: gem pristine unf_ext --version 0.0.7.6
/usr/share/gems/gems/openssl-2.1.2/lib/openssl/ssl.rb:20:in `<class:SSLContext>': uninitialized constant OpenSSL::SSL::TLS1_VERSION (NameError)
	from /usr/share/gems/gems/openssl-2.1.2/lib/openssl/ssl.rb:18:in `<module:SSL>'
	from /usr/share/gems/gems/openssl-2.1.2/lib/openssl/ssl.rb:17:in `<module:OpenSSL>'
	from /usr/share/gems/gems/openssl-2.1.2/lib/openssl/ssl.rb:16:in `<top (required)>'
	from /home/david/.rvm/rubies/ruby-2.3.7/lib/ruby/site_ruby/2.3.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	from /home/david/.rvm/rubies/ruby-2.3.7/lib/ruby/site_ruby/2.3.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	from /usr/share/gems/gems/openssl-2.1.2/lib/openssl.rb:21:in `<top (required)>'
	from /home/david/.rvm/rubies/ruby-2.3.7/lib/ruby/site_ruby/2.3.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	from /home/david/.rvm/rubies/ruby-2.3.7/lib/ruby/site_ruby/2.3.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	from /usr/share/vagrant/gems/gems/vagrant-2.1.2/lib/vagrant.rb:66:in `<top (required)>'
	from /home/david/.rvm/rubies/ruby-2.3.7/lib/ruby/site_ruby/2.3.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	from /home/david/.rvm/rubies/ruby-2.3.7/lib/ruby/site_ruby/2.3.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	from /usr/share/vagrant/gems/gems/vagrant-2.1.2/bin/vagrant:85:in `<top (required)>'
	from /usr/share/vagrant/gems/bin/vagrant:23:in `load'
	from /usr/share/vagrant/gems/bin/vagrant:23:in `<main>'
```

**Comment by secfigo** [comment]
Thanks @dspautz Fixed in #89
